name: Build and test
on:
  push:
    branches-ignore:
      - master
  workflow_dispatch:

jobs:
  linux-dev-build:
    permissions:
      contents: read
    uses: ./.github/workflows/build_linux.yml
    secrets:
      PIA_ACCOUNT_NAME: ${{ secrets.PIA_ACCOUNT_NAME }}
      PIA_ACCOUNT_PWD: ${{ secrets.PIA_ACCOUNT_PWD }}
    with:
      BRAND: pia

  linux-dev-arm-build:
    if: ${{ false }}
    permissions:
      contents: read
    uses: ./.github/workflows/build_linux_arm.yml
    with:
      BRAND: pia

  macos-dev-build:
    permissions:
      contents: read
    uses: ./.github/workflows/build_mac.yml
    secrets:
      PIA_ACCOUNT_NAME: ${{ secrets.PIA_ACCOUNT_NAME }}
      PIA_ACCOUNT_PWD: ${{ secrets.PIA_ACCOUNT_PWD }}
    with:
      BRAND: pia

  windows-dev-build:
    permissions:
      contents: read
    uses: ./.github/workflows/build_windows.yml
    with:
      BRAND: pia
